# Generated by Django 4.0.5 on 2022-06-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0003_shopuser_name_shopuser_wallet_alter_shopuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='datetime',
            new_name='date_created',
        ),
    ]
