# Generated by Django 4.0.5 on 2022-06-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0004_rename_datetime_refund_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='username',
        ),
    ]
