# Generated by Django 4.0.5 on 2022-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0009_alter_good_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['in_stock']},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='shopuser',
            options={},
        ),
    ]
