# Generated by Django 4.0.5 on 2022-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishop', '0012_alter_shopuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
